---
- name: CONFIG IBGP AND VPN 
  hosts: R1
  gather_facts: false

  tasks:
    - name: Configure BGP VPN 
      cisco.ios.ios_config:
        lines:
          - address-family ipv4 {{ item.vrf_name }}
          - neighbor {{ item.neighbor }} activate
          - neighbor {{ item.neighbor }} send-community
        parents:
          - router bgp {{ asn }}
      loop: "{{ peers }}"
