---
- name: OSPF AREA O V4
  hosts: R1,R2,R3,R4,R5,R6,R7,R8.R9
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Push OSPF interface parameters
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item.name }}"
            address_family: "{{ item.address_family }}"
        state: merged
      loop: "{{ ospf_interfaces }}"