---
- name: Configure Cisco Interface Level OSPF via Resource Module Loop
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Push OSPF interface parameters
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item.name }}"
            address_family: "{{ item.address_family }}"
        state: merged
      loop: "{{ ospf_interfaces }}"