device_interfaces:
  - name: GigabitEthernet0/0
    description: "Link R10 to R1"
    ip_address: "192.50.25.82"
    subnet_mask: "255.255.255.248"
  - name: POS3/0
    description: "LAN R10"
    ip_address: "192.50.25.33"
    subnet_mask: "255.255.255.240"
  - name: Loopback10
    description: "Loopback on router "
    ip_address: "10.10.10.10"
    subnet_mask: "255.255.255.255"