device_interfaces:
  - name: GigabitEthernet0/0
    description: "Link R12 to R3"
    ip_address: "192.50.25.106"
    subnet_mask: "255.255.255.252"
  - name: POS3/0
    description: "LAN R12"
    ip_address: "192.50.25.33"
    subnet_mask: "255.255.255.240"
  - name: Loopback10
    description: "Loopback on router "
    ip_address: "12.12.12.12"
    subnet_mask: "255.255.255.255"