device_interfaces:
  - name: GigabitEthernet0/0
    description: "Link R13 to R17"
    ip_address: "192.50.25.146"
    subnet_mask: "255.255.255.252"
  - name: POS3/0
    description: "LAN R13"
    ip_address: "192.50.25.193"
    subnet_mask: "255.255.255.240"
  - name: Loopback10
    description: "Loopback on router "
    ip_address: "13.13.13.13"
    subnet_mask: "255.255.255.255"