device_interfaces:
  - name: GigabitEthernet0/0
    description: "Link R3 to R12"
    ip_address: "192.50.25.105"
    subnet_mask: "255.255.255.252"
  - name: POS3/0
    description: "Link R3 TO R6"
    ip_address: "192.50.25.109"
    subnet_mask: "255.255.255.252"
  - name: Loopback10
    description: "Loopback on router "
    ip_address: "3.3.3.3"
    subnet_mask: "255.255.255.255"