- name: Configure Interfaces on Cisco IOS
  hosts: R1
  gather_facts: no
  tasks:
    - name: Add ip address 
      cisco.ios.ios_config:
        lines:
          - description {{ item.description }}
          - ip address {{ item.ip_address }} {{ item.subnet_mask }}
          - no shutdown
        parents: "interface {{ item.name }}"
      loop: "{{ device_interfaces }}"
    - name: Save config
      cisco.ios.ios_config:
        save_when: modified