- name: Configure Interfaces on Cisco IOS
  hosts: R1
  gather_facts: no
  tasks:
    - name: Save running configuration to NVRAM
      cisco.ios.ios_command:
        commands:
          - write memory