- name: Manage Cisco Device Banners
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Configure the MOTD banner
      cisco.ios.ios_banner:
        banner: motd
        state: present
        text: |
          ******************************************************
          WARNING: Authorized access only.
          All actions are monitored and recorded.
          ******************************************************