ospf_interfaces:

  - name: POS3/0
    address_family:
      - afi: ipv4
        process:
          id: 10
          area_id: 0
          autoconfig: true
          sync: true
mpls_label_ranges:
  - min_label: 100
  - max_label: 199