ospf_interfaces:
  - name: POS3/0
    address_family:
      - afi: ipv4
        process:
          id: 10
          area_id: 0
  - name: POS4/0
    address_family:
      - afi: ipv4
        process:
          id: 10
          area_id: 0
